FROM python:3.12.3

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

# Copy poetry files first for better caching
COPY pyproject.toml poetry.lock ./

# Install Poetry and dependencies
RUN pip install --upgrade pip \
    && pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry install --no-root

# Copy the project files
COPY ./project1 ./project1
COPY ./tests ./tests

# Change the CMD to explicitly use uvicorn
CMD ["poetry", "run", "uvicorn", "project1.main:app", "--host", "0.0.0.0", "--port", "8000"]