FROM python:3.12.3

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONPATH=/app

WORKDIR /app

# Copy poetry files first for better caching
COPY pyproject.toml poetry.lock ./

# Install Poetry and dependencies
RUN pip install --upgrade pip \
    && pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry lock \
    && poetry install --no-root

# Copy the entire project
COPY . .

# Install the project
RUN poetry lock \
    && poetry install 

CMD ["poetry", "run", "uvicorn", "project1.main:app", "--host", "0.0.0.0", "--port", "8000"]