# version "1.0"
# this is the overall docker-compose file which will be used to run the entire project
# this is to contanerize the entire project

# version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi_app
    environment:
      DB_HOST: db  # Use service name inside Docker
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"  # Expose FastAPI port for internal use (optional for development)
    networks:
      - app_network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_proxy
    ports:
      - "80:80"  # Expose Nginx port for external use
    depends_on:
      - fastapi
    networks:
      - app_network

  db:
    image: postgres:13
    container_name: postgres_db_Project1
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"  # Expose Postgres port for internal use (optional for development)
    networks:
      - app_network

networks:
  app_network:
    driver: bridge    # Use bridge network driver for the app network this is default network driver for docker-compose

    # as for why we need network, it is because we need to connect the fastapi and nginx containers together also 
    # we need to connect the fastapi container to the database container.
